import { Product } from "./types";

export const products: Product[] = [
  {
    id: "p1",
    slug: "silk-press-bundle",
    name: "Silk Press Bundle",
    category: "hair",
    subcategory: "Human Hair Bundles",
    price: 45000,
    compareAtPrice: 58000,
    description:
      "100% virgin human hair, double-wefted for fullness and a natural silk-press finish that holds through humidity.",
    details: ["100% virgin human hair", "Double-wefted", "12–24 inch options", "Dyeable & heat-safe up to 180°C"],
    swatches: [
      { name: "Natural Black", hex: "#1A1210" },
      { name: "Dark Brown", hex: "#3B2418" },
      { name: "Honey Blonde", hex: "#B8863B" },
    ],
    badge: "Bestseller",
    rating: 4.8,
    reviewCount: 214,
  },
  {
    id: "p2",
    slug: "hd-lace-closure-wig",
    name: "HD Lace Closure Wig",
    category: "hair",
    subcategory: "Wigs",
    price: 85000,
    description: "Pre-plucked HD lace closure wig with a natural hairline and breathable cap construction.",
    details: ["4x4 HD lace closure", "Pre-plucked hairline", "150% density", "Adjustable elastic band"],
    swatches: [
      { name: "Natural Black", hex: "#1A1210" },
      { name: "Chestnut", hex: "#6B3A28" },
    ],
    badge: "New",
    rating: 4.6,
    reviewCount: 98,
  },
  {
    id: "p3",
    slug: "braiding-hair-jumbo",
    name: "Jumbo Braiding Hair",
    category: "hair",
    subcategory: "Braiding Hair",
    price: 3500,
    description: "Kanekalon-blend braiding hair, low-shine finish, holds tight coils without slipping.",
    details: ["Kanekalon blend", "82 inches per pack", "Low shine", "Flame-retardant fiber"],
    swatches: [
      { name: "Jet Black", hex: "#0F0B0A" },
      { name: "Burgundy", hex: "#7A2333" },
      { name: "Ash Brown", hex: "#5A4636" },
    ],
    rating: 4.5,
    reviewCount: 340,
  },
  {
    id: "p4",
    slug: "matte-velvet-lipstick",
    name: "Matte Velvet Lipstick",
    category: "cosmetics",
    subcategory: "Lips",
    price: 6500,
    description: "Long-wear matte lipstick with a whipped, non-drying texture built for melanin-rich skin tones.",
    details: ["8-hour wear", "Non-drying formula", "Vitamin E enriched", "Vegan & cruelty-free"],
    swatches: [
      { name: "Terracotta", hex: "#B8663F" },
      { name: "Berry Wine", hex: "#7A2333" },
      { name: "Rosewood", hex: "#9A4A4A" },
      { name: "Nude Cocoa", hex: "#8B5A3C" },
    ],
    badge: "Bestseller",
    rating: 4.9,
    reviewCount: 512,
  },
  {
    id: "p5",
    slug: "hydrating-foundation",
    name: "Hydrating Skin-Tint Foundation",
    category: "cosmetics",
    subcategory: "Face",
    price: 12000,
    description: "Buildable, lightweight foundation with hyaluronic acid — deep, true-to-tone shade range.",
    details: ["24-shade range", "SPF 20", "Hyaluronic acid", "Natural satin finish"],
    swatches: [
      { name: "Deep Espresso", hex: "#3B2418" },
      { name: "Warm Amber", hex: "#8B5A3C" },
      { name: "Golden Caramel", hex: "#B8863B" },
      { name: "Rich Ebony", hex: "#1A1210" },
    ],
    rating: 4.7,
    reviewCount: 189,
  },
  {
    id: "p6",
    slug: "edge-control-gel",
    name: "Strong Hold Edge Control",
    category: "cosmetics",
    subcategory: "Hair Styling",
    price: 4200,
    description: "Flake-free edge control with 24-hour hold and a satin (not greasy) finish.",
    details: ["24-hour hold", "No white residue", "Castor oil enriched", "2.5 oz jar"],
    swatches: [{ name: "Classic", hex: "#2B1B14" }],
    badge: "Low Stock",
    rating: 4.4,
    reviewCount: 276,
  },
  {
    id: "p7",
    slug: "curl-defining-cream",
    name: "Curl Defining Cream",
    category: "hair",
    subcategory: "Hair Care",
    price: 7800,
    description: "Moisture-rich curl cream that defines coils and kinks without weighing hair down.",
    details: ["For 3A–4C curl types", "Shea butter base", "Sulfate-free", "8 oz tub"],
    swatches: [{ name: "Classic", hex: "#5A4636" }],
    rating: 4.6,
    reviewCount: 152,
  },
  {
    id: "p8",
    slug: "brow-sculpting-pomade",
    name: "Brow Sculpting Pomade",
    category: "cosmetics",
    subcategory: "Eyes",
    price: 5200,
    description: "Waterproof brow pomade for precise, natural-looking definition that lasts all day.",
    details: ["Waterproof", "Angled brush included", "Smudge-proof", "4 shade options"],
    swatches: [
      { name: "Ash Brown", hex: "#5A4636" },
      { name: "Espresso", hex: "#2B1B14" },
      { name: "Charcoal Black", hex: "#1A1210" },
    ],
    rating: 4.5,
    reviewCount: 87,
  },
];

export function getProductBySlug(slug: string) {
  return products.find((p) => p.slug === slug);
}

export function getRelated(product: Product, count = 4) {
  return products.filter((p) => p.category === product.category && p.id !== product.id).slice(0, count);
}
